# -*- coding: utf-8 -*-
"""Sahana_Bannigol_MoviesDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yg-V7PQ1v8yKDdnHnGl7VA8HBqIG8Pxt

Importing SQLite3 Module and Connecting to the Database and Creating a Database
"""

import sqlite3
connection = sqlite3.connect("movies.db")

"""Creating a cursor to execute queries and Creating a Table"""

cursor = connection.cursor()
cursor.execute(" CREATE TABLE movies (name TEXT, actor TEXT, actress TEXT, director TEXT, year INTEGER)")

"""Inserting Values into the Movies Table"""

cursor.execute("INSERT INTO movies VALUES('Om Shanti Om','SRK','Deepika Padukone','Farah Khan',2007)")
cursor.execute("INSERT INTO movies VALUES('3 Idiots', 'Aamir Khan','Kareena Kapoor','RajKumar Hirani',2009)")
cursor.execute("INSERT INTO movies VALUES('Veer-Zara','SRK','Preity Zinta','Yash Chopra',2004)")
cursor.execute("INSERT INTO movies VALUES('Main Hoon Na','SRK','Sushmitha Sen','Farah Khan',2004)")
cursor.execute("INSERT INTO movies VALUES('Lagaan','Aamir Khan','Gracy Singh','Aushutosh Gowariker',2008)")

"""Reading Data from the Database and Simple SELECT statement to query all rows from the Movies table"""

rows = cursor.execute("SELECT * FROM movies").fetchall()
for i in rows:
  name,actor,actress,director,year = i
  print(name+"\t"+actor+"\t"+actress+"\t"+director+"\t"+str(year))

"""Query with parameter like actor name to select movies based on the actor's name."""

actor_rows = cursor.execute("SELECT * FROM movies WHERE actor='SRK'").fetchall()
for i in actor_rows:
  name,actor,actress,director,year = i
  print(name+"\t"+actor+"\t"+actress+"\t"+director+"\t"+str(year))